config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/', to: 'statics#admin_index', as: 'panel'
    resources :discs
    resources :authors
    resources :genres
    post "tracks/:id", to: 'tracks#create', as: 'disc_for_tracks'
    put "tracks/:id", to: 'tracks#updateSampleUrl', as: 'edit_track'
    delete "tracks/:id", to: "tracks#destroy", as: 'track_destroy'
    post "attachments/:attachmentable_type/:attachmentable_id", to: 'attachments#create', as: 'attachment'
    delete "attachments/:id", to: "attachments#destroy", as: 'attachment_destroy'
    resources :tracks, only:[:edit,:update] do
      member do
        get :setPrice
      end
    end
    resources :attachments, only:[:create]
    resources :featureds
    resources :interpreters
  end

  get 'orders/download/:url', to: 'orders#download', as: 'download'
  root 'statics#homepage'
  resource :user
  resources :sessions, only: [:create,:destroy,:new]

  resources :discs, only: [:show] do
    collection do
      get :search, to: 'discs#search'
      get 'search/:disc', to: 'discs#search'
    end
  end

  get 'checkout', to: 'checkout#show', as: 'checkout'
  resource :payments, only: [:create]
  get 'payments/confirm', to: 'payments#confirm', as: 'payment_confirm'
  get 'payments/cancel', to: 'payments#cancel', as: 'payment_cancel'
  resources :orders, only: [:show]
  resource :profile, only: [:show]
  resources :catalogs, only: [:show,:index]
  get 'acerca_de', to: 'statics#acerca_de', as: 'acerca_de'
  get 'locals/set/:id',to: 'locals#set',as:'change_language'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  validates :url, presence: true
  validates :amazonId, presence: true, uniqueness: true

  belongs_to :attachmentable, polymorphic: true
end

app/models/author.rb
class Author < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_one :attachment, as: :attachmentable

  has_many :shelves, dependent: :destroy
  has_many :discs, through: :shelves
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :order
  belongs_to :detailmentable, polymorphic: true
end

app/models/disc.rb
class Disc < ActiveRecord::Base
  translates :title,:description

  validates :title, presence: true
  validates :price, presence: true
  has_many :attachments, as: :attachmentable
  has_many :tracks
  belongs_to :genre
  has_many :performances
  has_many :interpreters, :through => :performances

  has_many :shelves
  has_many :authors, :through => :shelves

  def self.search_by_title title
    where("title_es ILIKE ? or title_en LIKE ?", "%#{title}%","%#{title}%")
  end

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  translates :name

  validates :name, presence: true

  has_many :discs
  has_one :attachment, as: :attachmentable
end

app/models/interpreter.rb
class Interpreter < ActiveRecord::Base
  translates :name

  validates :name, :presence => true

  has_many :performances, dependent: :destroy
  has_many :tracks, through: :performances
  has_many :discs, through: :performances
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :details
  has_many :discs, :through => :details, :source => :detailmentable, :source_type => 'Disc'
  has_many :tracks, :through => :details, :source => :detailmentable, :source_type => 'Track'
  belongs_to :user
  has_one :payment
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
end

app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :track
  belongs_to :interpreter
  belongs_to :disc
end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
  belongs_to :author
  belongs_to :disc
end

app/models/track.rb
class Track < ActiveRecord::Base

  validates :url, presence: true
  validates :amazonId, presence: true, uniqueness: true
  validates :price, numericality: true


  belongs_to :disc
  has_many :performances, dependent: :destroy
  has_many :interpreters, :through => :performances
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :email, case_sensitive: false
  validates_length_of :password, minimum: 5, on: :create
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_confirmation_of :email

  has_many :payments
  has_many :orders

end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_adminMenu.html.erb
<style>
  a{
    color: black;
  }
</style>

<nav class="navbar navbar-default main-menu">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Urtext Online</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to  "Discs",admin_discs_path %></li>
        <li><%= link_to  "Artista",admin_authors_path %></li>
        <li><%= link_to "Compositor", admin_interpreters_path %></li>
        <li><%= link_to  "Generos",admin_genres_path %></li>
        <li><%= link_to "Destacados", admin_featureds_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/shared/_cover.html.erb
<section class="col-md-3">
  <section class="disc-cover-container">
    <img src="http://dummyimage.com/270x250" alt="" class="img-responsive">
    <section class="discButtons text-center center-block">
      <a href="#"><i class="fa fa-shopping-cart fa-lg" ></i></a>
      <a href="#"><i class="fa fa-play fa-lg" ></i></a>
    </section><!--/discButtons -->
  </section>

app/views/shared/_footer.html.erb
<hr>

<footer>
  <section class="container">
    <section class="row">
      <section class="col-md-4 text-center">
        <%= image_tag (asset_url 'footer-logo.png'), class:'center-block' %>
      </section><!-- /col md 4 -->


      <section class="col-md-4 text-center">
        <ul>

          <li><a href="Acerca de nosotros"></a><%= link_to t("footer_acerca_de"), acerca_de_path %></li>
          <a href="<%= asset_path ("politica-privacidad-urtext.pdf") %>"><li><%= t("footer_politica") %></li></a>
          <li><%= t("footer_terminos") %></li>
          <li><%= t("footer_contacto") %></li>

        </ul>
      </section><!-- /col md 4 -->

      <section class="col-md-4 text-center">
        <section class="row">
          <i class="fa fa-cc-paypal fa-2x"></i>
        </section>

        <section class="row">
          <a href="https://www.facebook.com/pages/urtextonlinecom/180339158663338"><i class="fa fa-facebook-official fa-2x"></i></a>
          <a href="http://www.youtube.com/user/urtextonline/videos?flow=grid&view=0"><i class="fa fa-youtube-square fa-2x"></i></a>
        </section>
      </section><!-- /col md 4 -->
    </section><!--/row-->
  </section>
</footer>

app/views/shared/_language.erb
<div class="alert idioma-select alert-default alert-dismissible fade in text-center" role="alert" >
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
  </div>

app/views/shared/_menu.html.erb
<nav class="navbar navbar-default main-menu">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">
        <section class="row text-center"> <%= image_tag asset_url("logo.png") %></section>
      </a>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to image_tag('mexico-flag.png' , class: ('activeLang' if session[:locale] == "es")), change_language_path('es')  %> </li>
        <li><%= link_to  image_tag('united-states-flag.png', class: ('activeLang' if session[:locale] == "en")), change_language_path('en') %> </li>

        <li><a href="<%= catalogs_path() %>"><%= t("menu_catalogo") %></a></li>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= t("menu_categorias") %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% Genre.where('collection = false').each do |genre| %>
                <li><a href="<%= catalog_path(genre.id) %>"><%= genre.name %></a></li>
              <% end %>
            </ul>
          </li>
          <li><a target="_blank" href="https://www.facebook.com/App-En-concierto-La-orquesta-a-detalle-1632153577035107/"><%= t("menu_multimedia") %></a></li>

          <% if current_user %>
           <li> <%=  link_to  t("menu_mi_cuenta") , profile_path  %></li>
           <li><%= link_to t("menu_cerrar_sesion"), session_path(session[:user_id]), method: :delete %></li>
          <% else %>
            <li>
              <a href="#" id="popover"><%= t("menu_iniciar_sesion") %></a>

                <div id="popover-content" class="hide">
                  <%= form_tag sessions_path, role: 'form'  do |f| %>

                    <div class="form-group">
                      <%= text_field_tag :email, nil,class: 'form-control', placeholder: t('menu_email') %>
                    </div>
                    <div class="form-group">
                      <%= password_field_tag :password, nil,class: 'form-control', placeholder: t('menu_contraseña') %>
                    </div>
                      <button type="submit" class="btn btn-primary center-block" style="background-color:#1449E3"><%= t("menu_iniciar_sesion") %></button>
                  <% end %><br>
                  <p>
                    <%= t("menu_nuevo") %><%= link_to t('menu_crear_cuenta'), new_user_path, style:'color:#1449E3;text-decoration:underline' %>
                  </p>
                </div></li>
            <li><%= link_to t('menu_crear_cuenta'), new_user_path unless current_user %></li>
          <% end %>

        </ul>

      </ul>

      <%= form_tag search_discs_path,method: :get, class:'navbar-form  navbar-right hidden-xs' , role: 'search' do %>
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search" name="disc">
        </div>
          <button type="submit" class="btn btn-default">
            <i class="fa fa-search"></i>
          </button>

      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <a href="<%= checkout_path %>">
        <li> <section class="shopping-cart">
           <i class="fa fa-shopping-cart " ></i>
           <span id="cookie_counter">
             <% if cookies[:basket].blank? %>
               <%= "0" %>
             <% else %>
              <%= JSON.parse(cookies[:basket]).count %>
            <% end %>

           </span>
         </section></li>
         </a>
      </ul>

    </div><!-- /.navbar-collapse -->

  </div>
</nav>

<div class="alert alert-success " id="purchaseMsg">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <p><strong><%= t("cart_added_item") %>.</strong> <%= t("cart_goto") %> <%= link_to "Checkout", checkout_path %></p>
</div>

<div class="alert alert-warning" id="removeMsg">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <strong><%= t("cart_removed_item") %></strong>
</div>

<script>
$('#popover').popover({
  html : true,
  placement: 'bottom',
  title: function() {
    return $("#popover-head").html();
  },
  content: function() {
    return $("#popover-content").html();
  }
});
</script>

app/views/shared/_ventajas.html.erb
<section class="container indexAdvantages">
  <section class="row">

  <section class="col-md-4 text-center">
    <i class="fa fa-users fa-3x"></i>
    <p><%= t('home_page_1st_feature') %></p>
  </section>

  <section class="col-md-4 text-center">
    <i class="fa fa-headphones fa-3x"></i>
    <p><%= t('home_2nd_feature') %></p>
  </section>

  <section class="col-md-4 text-center">
    <i class="fa fa-music fa-3x"></i>
    <p><%= t('home_3rd_feature') %></p>
  </section>

</section><!-- /row -->
</section><!-- index advantages -->