config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/', to: 'statics#admin_index', as: 'panel'
    resources :discs
    resources :authors
    resources :genres
    post "tracks/:id", to: 'tracks#create', as: 'disc_for_tracks'
    put "tracks/:id", to: 'tracks#updateSampleUrl', as: 'edit_track'
    delete "tracks/:id", to: "tracks#destroy", as: 'track_destroy'
    post "attachments/:attachmentable_type/:attachmentable_id", to: 'attachments#create', as: 'attachment'
    delete "attachments/:id", to: "attachments#destroy", as: 'attachment_destroy'
    resources :tracks, only:[:edit,:update] do
      member do
        get :setPrice
      end
    end
    resources :attachments, only:[:create]
    resources :featureds
    resources :interpreters
  end

  get 'orders/download/:url', to: 'orders#download', as: 'download'
  root 'statics#homepage'
  resource :user
  resources :sessions, only: [:create,:destroy,:new]

  resources :discs, only: [:show] do
    collection do
      get :search, to: 'discs#search'
      get 'search/:disc', to: 'discs#search'
    end
  end

  get 'checkout', to: 'checkout#show', as: 'checkout'
  resource :payments, only: [:create]
  get 'payments/confirm', to: 'payments#confirm', as: 'payment_confirm'
  get 'payments/cancel', to: 'payments#cancel', as: 'payment_cancel'
  resources :orders, only: [:show]
  resource :profile, only: [:show]
  resources :catalogs, only: [:show,:index]
  get 'acerca_de', to: 'statics#acerca_de', as: 'acerca_de'
  get 'locals/set/:id',to: 'locals#set',as:'change_language'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  validates :url, presence: true
  validates :amazonId, presence: true, uniqueness: true

  belongs_to :attachmentable, polymorphic: true
end

app/models/author.rb
class Author < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_one :attachment, as: :attachmentable

  has_many :shelves, dependent: :destroy
  has_many :discs, through: :shelves
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :order
  belongs_to :detailmentable, polymorphic: true
end

app/models/disc.rb
class Disc < ActiveRecord::Base
  translates :title,:description

  validates :title, presence: true
  validates :price, presence: true
  has_many :attachments, as: :attachmentable
  has_many :tracks
  belongs_to :genre
  has_many :performances
  has_many :interpreters, :through => :performances

  has_many :shelves
  has_many :authors, :through => :shelves

  def self.search_by_title title
    where("title_es ILIKE ? or title_en LIKE ?", "%#{title}%","%#{title}%")
  end

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  translates :name

  validates :name, presence: true

  has_many :discs
  has_one :attachment, as: :attachmentable
end

app/models/interpreter.rb
class Interpreter < ActiveRecord::Base
  translates :name

  validates :name, :presence => true

  has_many :performances, dependent: :destroy
  has_many :tracks, through: :performances
  has_many :discs, through: :performances
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :details
  has_many :discs, :through => :details, :source => :detailmentable, :source_type => 'Disc'
  has_many :tracks, :through => :details, :source => :detailmentable, :source_type => 'Track'
  belongs_to :user
  has_one :payment
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
end

app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :track
  belongs_to :interpreter
  belongs_to :disc
end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
  belongs_to :author
  belongs_to :disc
end

app/models/track.rb
class Track < ActiveRecord::Base

  validates :url, presence: true
  validates :amazonId, presence: true, uniqueness: true
  validates :price, numericality: true


  belongs_to :disc
  has_many :performances, dependent: :destroy
  has_many :interpreters, :through => :performances
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :email, case_sensitive: false
  validates_length_of :password, minimum: 5, on: :create
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_confirmation_of :email

  has_many :payments
  has_many :orders

end

app/controllers/admin/discs_controller.rb
class Admin::DiscsController < ApplicationController
  before_action :require_login
  before_action :admin?
  before_action :set_admin_disc, only: [:show, :edit, :update, :destroy]

  # GET /admin/discs
  # GET /admin/discs.json
  def index
    @admin_discs = Disc.all

  end

  # GET /admin/discs/1
  # GET /admin/discs/1.json
  def show
  end

  # GET /admin/discs/new
  def new
    @admin_disc = Disc.new
  end

  # GET /admin/discs/1/edit
  def edit
    @genres = Genre.all
    @authors = Author.all
    @tracks = Track.where(:disc_id => params[:id]).order(:title)
    @covers = Attachment.where(:attachmentable_id => params[:id]).where(:attachmentable_type => 'Disc')
  end

  # POST /admin/discs
  # POST /admin/discs.json
  def create
    @admin_disc = Disc.new(admin_disc_params)
    respond_to do |format|
      if @admin_disc.save
        format.html { redirect_to admin_disc_url(@admin_disc) , notice: 'Disc was successfully created.' }
        format.json { render :show, status: :created, location: @admin_disc }
      else
        format.html { render :new }
        format.json { render json: @admin_disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/discs/1
  # PATCH/PUT /admin/discs/1.json
  def update
    respond_to do |format|
      if @admin_disc.update(admin_disc_params)
        format.html { redirect_to admin_disc_url(@admin_disc), notice: 'Disc was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_disc }
      else
        format.html { render :edit }
        format.json { render json: @admin_disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/discs/1
  # DELETE /admin/discs/1.json
  def destroy
    @admin_disc.destroy
    respond_to do |format|
      format.html { redirect_to admin_discs_url, notice: 'Disc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_disc
      @admin_disc = Disc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_disc_params
      params.fetch(:disc, {}).permit(:title_es,:title_en,:price,:description_es,:description_en,:genre_id ,:discUrl,:author_ids => [],:interpreter_ids => [])
      #params.require(:disc).permit(:title,:price,:description)
    end
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
  before_action :set_disc, only: [:show]

  def show
    @tracks = @disc.tracks.order(:title)
  end

  def search
    @discs = Disc.search_by_title params[:disc]
  end

  private
  def set_disc
    @disc = Disc.find(params[:id])
  end
end

app/helpers/admin/discs_helper.rb
module Admin::DiscsHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/discs/_form.html.erb
<%= form_for [:admin,@admin_disc] do |f| %>
  <% if @admin_disc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_disc.errors.count, "error") %> prohibited this admin_disc from being saved:</h2>

      <ul>
      <% @admin_disc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">


    <section class="col-md-4">
      <h3>Genero</h3>
    <%= f.collection_select :genre_id, Genre.order(:name_es), :id, :name, {:selected => @admin_disc.genre_id.to_s}, {class:'form-control'} %>
    </section>

    <section class="col-md-4">
      <h3>Artista</h3>
    <%= f.collection_select :author_ids, Author.order(:name), :id, :name, {:selected => @admin_disc.author_ids.collect {|author| author}}, {class:'form-control', multiple:'true',style:'height:300px'} %>
    </section>

    <section class="col-md-4">
      <h3>Compositor</h3>
    <%= f.collection_select :interpreter_ids, Interpreter.order(:name_es), :id, :name, {:selected => @admin_disc.interpreter_ids.collect { |interpreter| interpreter }}, {class:'form-control', multiple:'true', style:'height:300px'} %>
    </section>

    <% Disc.locale_columns(:title,:description).each do |column| %>
        <p>
          <%= f.label column %>
          <%= f.text_field column, {class:'form-control'} %>
        </p>
    <% end %>

    <section class="form-group">
      <%= f.label :title, "Titulo" %>
      <%= f.text_field :title, {class:'form-control'}%>
    </section>

    <section class="form-group">
      <%= f.label :description, "Descripcion" %>
      <%= f.text_area :description, {class:'form-control'} %>
    </section>


    <section class="form-group">
      <%= f.label :price, "Precio" %>
      <%= f.text_field :price, {class:'form-control'} %>
    </section>


    <%= f.submit 'Enviar', {class:'btn btn-primary'} %>
  </div>
<% end %>

app/views/admin/discs/edit.html.erb
<%= render 'shared/adminMenu' %>

<h1>Editing Admin Disc</h1>

<%= render 'form' %>

<h1>Full Disc</h1>
<% if @admin_disc.discUrl %>
          <%= @admin_disc.discUrl %>
    <% else %>
      <%= s3_uploader_form callback_url: admin_disc_path, callback_method: :put, callback_param: "disc[discUrl]", id: "full-discs-uploader" do %>
        <%= file_field_tag :file,accept: 'application/zip', multiple: false, data: { url: s3_uploader_url },id: 'full-disc-uploader' %>
    <% end %>
<% end %>


<h1>Upload tracks</h1>
<%= s3_uploader_form callback_url: admin_disc_for_tracks_path, callback_param: "disc[track_url]", id: "tracks-uploader" do %>
  <%= file_field_tag :file,accept: 'audio/*', multiple: true, data: { url: s3_uploader_url },id: 'track-uploader' %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div id="file-{%=o.unique_id%}" class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>

<h1>Upload covers</h1>
<%= s3_uploader_form callback_url: admin_attachments_path + "/Disc/" + @admin_disc.id.to_s, callback_param: "disc[attachment_url]", id: "covers-uploader" do %>
  <%= file_field_tag :file,accept: 'image/*', multiple: true, data: { url: s3_uploader_url },id: 'track-uploader' %>
<% end %>

<script id="template-upload" type="text/x-tmpl">
<div id="file-{%=o.unique_id%}" class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
</div>
</script>


<h2>Current tracks</h2>

<table class="table">

  <% @tracks.each do |track| %>

    <tr>
      <td><%= track.title %></td>
      <td><% if track.sampleUrl %>
                <%= track.sampleUrl %>
          <% else %>
            <%= s3_uploader_form callback_url: admin_edit_track_path(track.id), callback_method: :put, callback_param: "update[sampleUrl]", class: "samples-uploader" do %>
              <%= file_field_tag :file,accept: 'audio/*', multiple: false, data: { url: s3_uploader_url },class: 'sample-uploader' %>
            <% end %>
          <% end %>
        </td>
      <td><%= link_to "Listen", track.url %></td>
      <td><%= link_to "Edit",edit_admin_track_path(track.id) %></td>
      <td><%= link_to "Delete", admin_track_destroy_path(track.id), method: :delete  %></td>
    </tr>

  <% end %>
</table>

<h2>Current Covers</h2>

<section>
  <% @covers.each do |cover| %>
    <%= image_tag cover.url, size: '300x300' %>
    <%= link_to "Delete", admin_attachment_destroy_path(cover.id), method: :delete  %>

  <% end %>
</section>

<br>
<%= link_to 'Show', admin_disc_path(@admin_disc) %> |
<%= link_to 'Back', admin_discs_path %>

app/views/admin/discs/index.html.erb
<%= render 'shared/adminMenu' %>

<p id="notice"><%= notice %></p>

<h1>Listing Admin Discs</h1>
<hr>

<%= link_to 'New Disc', new_admin_disc_path,{ class:'btn btn-primary' } %>

<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_discs.each do |admin_disc| %>
      <tr>
        <td><%= admin_disc.title %></td>
        <td><%= link_to 'Edit', edit_admin_disc_path(admin_disc) %></td>
        <td><%= link_to 'Destroy', admin_disc_path(admin_disc.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/discs/new.html.erb
<%= render 'shared/adminMenu' %>

<h1>New Admin Disc</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_discs_path %>

app/views/admin/discs/show.html.erb
<%= render 'shared/adminMenu' %>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_disc_path(@admin_disc) %> |
<%= link_to 'Back', admin_discs_path %>

app/views/discs/search.html.erb
<%= render 'shared/menu' %>

<article class="container heightFix">

  <h1 class="space20px">Resultados</h1>


  <section class="col-md-9 " id="discCategory">

    <% @discs.each do |disc| %>
        <audio preload="false" class="trackPlayer" controls="controls" id="track-<%= disc.tracks.first.try(:id) %>">
          <source src="<%= disc.tracks.first.try(:sampleUrl)  %>" type="audio/mpeg" auto="false" />
        </audio>
    <section class="col-md-4 disc"  data-price="<%= disc.price %>">
      <section class="disc-cover-container">
        <a href="<%= disc_path(disc.id) %>"><img src="<%= disc.attachments.first.try(:url) %>" alt="" class="img-responsive"></a>
        <section class="discButtons text-center center-block">
          <a href="#"  class="favoriteButton" number="<%= disc.id %>", type='disc'><i class="fa fa-shopping-cart fa-lg" ></i></a>
          <a href="#" data-track="<%= disc.tracks.first.try(:id) %>" class="playerButtons"><i class="fa fa-play fa-lg"></i></a>
        </section><!--/discButtons -->
      </section>

      <section class="disc-details">
        <h4><%= disc.title %></h4>
        <h4><%= disc.genre.name %></h4>
        <h3><%= number_to_currency disc.price %></h3>
      </section>
    </section> <!--/col md 3-->
  <% end %>

  </section><!-- disc category -->

</article>
<%= render 'shared/footer' %>
<script>
  $(".playerButtons").click(function(){

    var trackToPlay  = $(this).data("track");
    var player = document.getElementById("track-"+trackToPlay);
    if (player.paused == false) {
      player.pause();
      $(this).children("i").addClass('fa-play');
      $(this).children("i").removeClass('fa-pause');

    } else {
      player.play();
      $(this).children("i").removeClass('fa-play');
      $(this).children("i").addClass('fa-pause');
    }
    return false;
  });
</script>

app/views/discs/show.html.erb
<%= render 'shared/menu' %>

<article class="jumbotron disc-big-image" style="background-image:url('<%= @disc.attachments.first.try(:url) %>')"></article>

<article class="container disc-container">

  <section class="disc-cover">
    <img src="<%= @disc.attachments.first.try(:url) %>" class="disc-details-cover center-block" alt="">
  </section>

  <section class="disc-detail text-center col-md-6 col-md-push-3">
    <h2><%= @disc.title %></h2>
    <h5><% @disc.authors.each do |author| %>
          <%= author.try(:name) %> /
      <% end %>
      <a href="#" class="disc-category"><%= @disc.genre.name %> </a>
    </h5>
    <p><%= @disc.description %></p>
    <h1 class="space20px"><%= number_to_currency(@disc.price) %></h1>
    <p><a href="#" class="btn btn-primary favoriteButton" number="<%= @disc.id %>", type='disc' style="background-color:#1449E3">Añadir Al carrito</a>
    <a href="#" class="btn btn-primary " id="comprar_btn" number="<%= @disc.id %>", type='disc' style="background-color:#1449E3">Comprar el disco completo</a></p>

  </section>

  <section class="track-container col-md-12">

    <% @tracks.each do |track| %>
      <section class="track-detail row">
        <audio preload="false" class="trackPlayer" controls="controls" id="track-<%= track.id %>">
          <source src="<%= track.sampleUrl %>" type="audio/mpeg" auto="false" />
        </audio>
        <section class="col-md-8">
          <h4><%= track.title %></h4>

          <h5><%= track.interpreters.map { |interpreter| interpreter.name }.join("/ ") %></h5>
        </section>

        <section class="col-md-2">
          <h3 class="disc-price"><%= number_to_currency(track.price) %></h3>
        </section>

        <section class="col-md-2 track-actions text-center">
          <a href="#" class="favoriteButton" number="<%= track.id %>", type='track'>
            <i class="fa fa-cart-plus fa-lg"></i>
          </a>
          <a href="#" data-track="<%= track.id %>" class="playerButtons"><i class="fa fa-play fa-lg"></i></a>
        </section>
      </section>
    <% end %>

  </section>
</article>

<script>
  $(".playerButtons").click(function(){

    var trackToPlay  = $(this).data("track");
    var player = document.getElementById("track-"+trackToPlay);
    if (player.paused == false) {
      player.pause();
      $(this).children("i").addClass('fa-play');
      $(this).children("i").removeClass('fa-pause');

  } else {
      player.play();
      $(this).children("i").removeClass('fa-play');
      $(this).children("i").addClass('fa-pause');
  }
  return false;
  });

  $("#comprar_btn").click(function(){

    emptyBasket();

    var id = parseInt($(this).attr("number"));
    var type = $(this).attr("type");
    var item = [{id: id, type: type}];
    Cookies("basket", JSON.stringify(item),{ expires: 365 });

    redirectToCheckout();

    console.log(Cookies("basket"));

  });


  function redirectToCheckout(){
    window.location.replace("../checkout");
  }

  function emptyBasket(){
    Cookies.set("basket",'[]') == [];
  }
</script>

<%= render 'shared/footer' %>