config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get '/', to: 'statics#admin_index', as: 'panel'
    resources :discs
    resources :authors
    resources :genres
    post "tracks/:id", to: 'tracks#create', as: 'disc_for_tracks'
    put "tracks/:id", to: 'tracks#updateSampleUrl', as: 'edit_track'
    delete "tracks/:id", to: "tracks#destroy", as: 'track_destroy'
    post "attachments/:attachmentable_type/:attachmentable_id", to: 'attachments#create', as: 'attachment'
    delete "attachments/:id", to: "attachments#destroy", as: 'attachment_destroy'
    resources :tracks, only:[:edit,:update] do
      member do
        get :setPrice
      end
    end
    resources :attachments, only:[:create]
    resources :featureds
    resources :interpreters
  end

  get 'orders/download/:url', to: 'orders#download', as: 'download'
  root 'statics#homepage'
  resource :user
  resources :sessions, only: [:create,:destroy,:new]

  resources :discs, only: [:show] do
    collection do
      get :search, to: 'discs#search'
      get 'search/:disc', to: 'discs#search'
    end
  end

  get 'checkout', to: 'checkout#show', as: 'checkout'
  resource :payments, only: [:create]
  get 'payments/confirm', to: 'payments#confirm', as: 'payment_confirm'
  get 'payments/cancel', to: 'payments#cancel', as: 'payment_cancel'
  resources :orders, only: [:show]
  resource :profile, only: [:show]
  resources :catalogs, only: [:show,:index]
  get 'acerca_de', to: 'statics#acerca_de', as: 'acerca_de'
  get 'locals/set/:id',to: 'locals#set',as:'change_language'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/featured.rb
class Admin::Featured < ActiveRecord::Base
  translates :title

  has_one :attachment, as: :attachmentable
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base

  validates :url, presence: true
  validates :amazonId, presence: true, uniqueness: true

  belongs_to :attachmentable, polymorphic: true
end

app/models/author.rb
class Author < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_one :attachment, as: :attachmentable

  has_many :shelves, dependent: :destroy
  has_many :discs, through: :shelves
end

app/models/detail.rb
class Detail < ActiveRecord::Base
  belongs_to :order
  belongs_to :detailmentable, polymorphic: true
end

app/models/disc.rb
class Disc < ActiveRecord::Base
  translates :title,:description

  validates :title, presence: true
  validates :price, presence: true
  has_many :attachments, as: :attachmentable
  has_many :tracks
  belongs_to :genre
  has_many :performances
  has_many :interpreters, :through => :performances

  has_many :shelves
  has_many :authors, :through => :shelves

  def self.search_by_title title
    where("title_es ILIKE ? or title_en LIKE ?", "%#{title}%","%#{title}%")
  end

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  translates :name

  validates :name, presence: true

  has_many :discs
  has_one :attachment, as: :attachmentable
end

app/models/interpreter.rb
class Interpreter < ActiveRecord::Base
  translates :name

  validates :name, :presence => true

  has_many :performances, dependent: :destroy
  has_many :tracks, through: :performances
  has_many :discs, through: :performances
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :details
  has_many :discs, :through => :details, :source => :detailmentable, :source_type => 'Disc'
  has_many :tracks, :through => :details, :source => :detailmentable, :source_type => 'Track'
  belongs_to :user
  has_one :payment
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  belongs_to :order
end

app/models/performance.rb
class Performance < ActiveRecord::Base
  belongs_to :track
  belongs_to :interpreter
  belongs_to :disc
end

app/models/shelf.rb
class Shelf < ActiveRecord::Base
  belongs_to :author
  belongs_to :disc
end

app/models/track.rb
class Track < ActiveRecord::Base

  validates :url, presence: true
  validates :amazonId, presence: true, uniqueness: true
  validates :price, numericality: true


  belongs_to :disc
  has_many :performances, dependent: :destroy
  has_many :interpreters, :through => :performances
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates_presence_of :email, case_sensitive: false
  validates_length_of :password, minimum: 5, on: :create
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates_confirmation_of :email

  has_many :payments
  has_many :orders

end

app/controllers/admin/featureds_controller.rb
class Admin::FeaturedsController < ApplicationController
  before_action :set_admin_featured, only: [:show, :edit, :update, :destroy]

  # GET /admin/featureds
  # GET /admin/featureds.json
  def index
    @admin_featureds = Admin::Featured.all
  end

  # GET /admin/featureds/1
  # GET /admin/featureds/1.json
  def show
  end

  # GET /admin/featureds/new
  def new
    @admin_featured = Admin::Featured.new
  end

  # GET /admin/featureds/1/edit
  def edit
    @cover = Attachment.where(:attachmentable => @admin_featured).first
  end

  # POST /admin/featureds
  # POST /admin/featureds.json
  def create
    @admin_featured = Admin::Featured.new(admin_featured_params)

    respond_to do |format|
      if @admin_featured.save
        format.html { redirect_to @admin_featured, notice: 'Featured was successfully created.' }
        format.json { render :show, status: :created, location: @admin_featured }
      else
        format.html { render :new }
        format.json { render json: @admin_featured.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/featureds/1
  # PATCH/PUT /admin/featureds/1.json
  def update
    respond_to do |format|
      if @admin_featured.update(admin_featured_params)
        format.html { redirect_to @admin_featured, notice: 'Featured was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_featured }
      else
        format.html { render :edit }
        format.json { render json: @admin_featured.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/featureds/1
  # DELETE /admin/featureds/1.json
  def destroy
    @admin_featured.destroy
    respond_to do |format|
      format.html { redirect_to admin_featureds_url, notice: 'Featured was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_featured
      @admin_featured = Admin::Featured.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_featured_params
      params.require(:admin_featured).permit(:url, :title_es,:title_en)
    end
end

app/helpers/admin/featureds_helper.rb
module Admin::FeaturedsHelper
end

app/helpers/catalogs_helper.rb
module CatalogsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/featureds/_form.html.erb
<%= form_for(@admin_featured) do |f| %>
  <% if @admin_featured.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_featured.errors.count, "error") %> prohibited this admin_featured from being saved:</h2>

      <ul>
      <% @admin_featured.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% Admin::Featured.locale_columns(:title).each do |column| %>
        <p>
          <%= f.label column %>
          <%= f.text_field column %>
        </p>
    <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<td><% if @cover %>
      <%= image_tag @cover.url, size: "300x300" %>
      <%= link_to "Delete", admin_attachment_destroy_path(@cover.id), method: :delete  %>
    <% else %>
      <%= s3_uploader_form callback_url: admin_attachments_path + "/Admin::Featured/" + @admin_featured.id.to_s, callback_param: "genre[discUrl]", id: "attachment-uploader" do %>
        <%= file_field_tag :file,accept: 'image/*', multiple: false, data: { url: s3_uploader_url } %>
      <% end %>

    <% end %>
  </td>

  <script id="template-upload" type="text/x-tmpl">
  <div id="file-{%=o.unique_id%}" class="upload">
    {%=o.name%}
    <div class="progress"><div class="bar" style="width: 0%"></div></div>
  </div>
  </script>

app/views/admin/featureds/edit.html.erb
<%= render 'shared/adminMenu' %>

<h1>Editing Admin Featured</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_featured %> |
<%= link_to 'Back', admin_featureds_path %>

app/views/admin/featureds/index.html.erb
<%= render 'shared/adminMenu' %>

<p id="notice"><%= notice %></p>

<h1>Listing Admin Featureds</h1>

<hr>
<%= link_to 'New Featured', new_admin_featured_path,{ class:'btn btn-primary' }  %>

<table class="table">
  <thead>
    <tr>
      <th>Url</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_featureds.each do |admin_featured| %>
      <tr>
        <td><%= admin_featured.url %></td>
        <td><%= admin_featured.title %></td>
        <td><%= link_to 'Show', admin_featured %></td>
        <td><%= link_to 'Edit', edit_admin_featured_path(admin_featured) %></td>
        <td><%= link_to 'Destroy', admin_featured, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/featureds/new.html.erb
<%= render 'shared/adminMenu' %>


<h1>New Admin Featured</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_featureds_path %>

app/views/admin/featureds/show.html.erb
<%= render 'shared/adminMenu' %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @admin_featured.url %>
</p>

<p>
  <strong>Title:</strong>
  <%= @admin_featured.title %>
</p>

<%= link_to 'Edit', edit_admin_featured_path(@admin_featured) %> |
<%= link_to 'Back', admin_featureds_path %>